### ISSUE TITLE
world_end will stay unload after I travel to it

### ISSUE THREAD

**Issue by chezpaul** [Multiverse/Multiverse-NetherPortals#120]
This happens every time I travel there.
First, I've given up on traveling there the normal minecraft way, it doesn't work (with the end portal).
 I just created portals in each dim with multiverse portals.

So, if I portal to the world_end and back to world, then world_end gets unloaded from multiverse and I can't go back until I restart the server.

That's it.
Thermos 1.7.10.58 with Forge 1614.

I get this error in the server log:

[15:19:24 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.5-b699
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:365) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalStateException: Lost reference to bukkit world 'Reminiscence_End'
	at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:496) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.getWorld(MVPortal.java:375) ~[?:?]
	at com.onarandombox.MultiversePortals.destination.PortalDestination.getLocation(PortalDestination.java:58) ~[?:?]
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:76) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 13 more
[15:19:26 ERROR]: Could not pass event PlayerMoveEvent to Multiverse-Portals v2.5-b699
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:365) [nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalStateException: Lost reference to bukkit world 'Reminiscence_End'
	at com.onarandombox.MultiverseCore.MVWorld.getCBWorld(MVWorld.java:496) ~[?:?]
	at com.onarandombox.MultiversePortals.MVPortal.getWorld(MVPortal.java:375) ~[?:?]
	at com.onarandombox.MultiversePortals.destination.PortalDestination.getLocation(PortalDestination.java:58) ~[?:?]
	at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:76) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
	... 13 more

**Comment by Jadiction** [comment]
Closing issue because it's an old post. If you are still running a Minecraft server and this persists, try updating all the Multiverse plugins and try again, otherwise please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
