### ISSUE TITLE
NoClassDefFoundError on startup

### ISSUE THREAD

**Issue by SlimeDog** [Multiverse/Multiverse-NetherPortals#134]
Spigot 1.13.1 latest
Multiverse-Core 2.6.0-b738
Multiverse-Portals 2.5.2-b765
WorldEdit 7.0.0-b3861

This error occurs on every server start.
```
[08:53:00] [Server thread/ERROR]: Error occurred while enabling Multiverse-Portals v2.5.2-SNAPSHOT-b765 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/bukkit/WorldEditAPI
        at com.onarandombox.MultiversePortals.WorldEditConnection.connect(WorldEditConnection.java:47) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.checkForWorldEdit(MultiversePortals.java:174) ~[?:?]
        at com.onarandombox.MultiversePortals.MultiversePortals.onEnable(MultiversePortals.java:141) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.bukkit.WorldEditAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar-2018-09-11-0432:git-Spigot-500ff5d-1cead62]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        ... 14 more
```

**Comment by Jadiction** [comment]
This is an old issue that depending on WorldEdit's wand. This was fixed in a later version that allows no WorldEdit dependency while also working with WorldEdit as well. Closing issue because it's an old post. If you are still running a Minecraft server and this persists, please don't hesitate to ask for support on our [Discord](https://discord.gg/NZtfKky) (quickest support) or submit a new issue.
