### ISSUE TITLE
Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN

### ISSUE THREAD

**Issue by ermitemc** [Multiverse/Multiverse-NetherPortals#136]
Each time i go into a nether portal it spams this error. I've seen other issues opened but noone says how to resolve this. I still can travel through portals

[17:03:18 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:986) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:18 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:986) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:21 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:2027) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.a(EntityHuman.java:1548) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2364) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.movementTick(EntityHuman.java:422) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:144) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:262) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1123) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:22 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:986) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:8) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:22 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.a(EntityLiving.java:2027) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.a(EntityHuman.java:1548) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2364) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.movementTick(EntityHuman.java:422) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:159) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:401) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.tick(PlayerConnection.java:144) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:262) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:129) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1123) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:22 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.utils.PermissionTools.playerHasMoneyToTeleport(Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lcom/onarandombox/MultiverseCore/api/MultiverseWorld;Lorg/bukkit/command/CommandSender;Lorg/bukkit/entity/Player;Z)Z
at com.onarandombox.MultiverseNetherPortals.listeners.MVNPEntityListener.onEntityPortalEnter(MVNPEntityListener.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-492]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-492]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.BlockPortal.a(BlockPortal.java:106) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.IBlockData.a(IBlockData.java:236) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.checkBlockCollisions(Entity.java:976) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.Entity.move(Entity.java:889) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:986) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-492]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:937) ~[patched_1.13.2.jar:git-Paper-492]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:835) ~[patched_1.13.2.jar:git-Paper-492]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[17:03:23 ERROR]: Could not pass event EntityPortalEnterEvent to Multiverse-NetherPortals v2.7.3-bUNKNOWN
java.lang.NoSuchMethodError:

**Comment by TBG-FR** [comment]
You can still travel through portals, but a Nether portal in world "world2" will send you to "world_nether" (and not, as it should, to "world2_nether" (or nowhere if it doesn't exist)).

I'll see if I have some time soon to check how it works and how to fix this in these plugins' code :)

**Comment by MrPistachios** [comment]
ERROR Could not pass event PlayerPortalEvent to Multiverse-NetherPortals v3.0.0-SNAPSHOT-b749
Getting the same issue on 1.14.2 with latest nether portal

**Comment by Jadiction** [comment]
This is fixed in the latest dev build at https://ci.onarandombox.com/view/Multiverse/job/Multiverse-NetherPortals/
