### ISSUE TITLE
error wont load 

### ISSUE THREAD

**Issue by random1167** [Multiverse/Multiverse-NetherPortals#137]
i built it with mvn today, any ideas ? the jar on bukkit also dose the same thing.
```
[05:06:11] [Server thread/ERROR]: Could not load 'plugins/Multiverse-NetherPortals-3.0.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:136) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:58) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:132) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_201]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:58) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:132) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
	... 6 more
```

**Comment by Jadiction** [comment]
Try the latest dev build (4.0.0). Make sure Multiverse-Core is updated as well with the 4.0.0 version.
