### ISSUE TITLE
Multiverse-NetherPortals not working.

### ISSUE THREAD

**Issue by 2266Flash** [Multiverse/Multiverse-NetherPortals#213]
I get this error:

[ERROR] Could not load 'plugins/Multiverse-NetherPortals-4.2.1.jar' in folder 'plugins'

org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: java.lang.NoClassDefFoundError: com/onarandombox/commandhandler/Command

at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]

at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

... 7 more

Caused by: java.lang.ClassNotFoundException: com.onarandombox.commandhandler.Command

at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]

at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]

at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3002-Spigot-138d451-085fe67]

... 7 more

**Comment by nicegamer7** [comment]
You need to update MV Core to the latest version.

**Comment by 2266Flash** [comment]
I have

**Comment by 2266Flash** [comment]
It is the latest version.

**Comment by nicegamer7** [comment]
Then please upload `latest.log` from the `logs` folder to something like pastebin.com and give us the link here.

**Comment by 2266Flash** [comment]
Unfortunately, I can not for privacy reasons. This is not my server and I am making it for a client.

**Comment by nicegamer7** [comment]
Then you can use mclo.gs, it will automatically remove any IP addresses.

**Comment by 2266Flash** [comment]
What would you gain from this?

**Comment by nicegamer7** [comment]
I will be able to tell what the problem is.

**Comment by 2266Flash** [comment]
I can not provide the full log. I have attached the error I get.

**Comment by nicegamer7** [comment]
Then I cannot help any further. That error means that MV Core is not up to date, and without the rest of the log I cannot verify that you are indeed using the latest version.

P.S. The latest version is `4.2.2`.

**Comment by 2266Flash** [comment]
I have tried using both.

**Comment by nicegamer7** [comment]
You tried using both what?

**Comment by 2266Flash** [comment]
Both versions. The one on Bukkit and 4.2.2

**Comment by nicegamer7** [comment]
The one on Bukkit is 4.2.2.

Check your plugins folder and make sure there is only **one** Multiverse-Core jar.

**Comment by 2266Flash** [comment]
It is Multiverse netherportals, not core.

**Comment by nicegamer7** [comment]
Multiverse NetherPortals depends on Multiverse-Core. The version of Multiverse-NetherPortals you have installed needs a version of Multiverse-Core of at least `4.2.0`.

Sorry if that was not clear.

**Comment by 2266Flash** [comment]
I have that.

**Comment by nicegamer7** [comment]
Then again, I cannot help you any further without the full log. Sorry.

**Comment by benwoo1110** [comment]
Closing the issue due to insufficient information. If you still face issue, then follow the issue template and open a new issue.
