### ISSUE TITLE
org.bukkit.plugin.java.JavaPlugin.getDescription()

### ISSUE THREAD

**Issue by bobhenl** [Multiverse/Multiverse-NetherPortals#252]
### Information

* **Server version:** 
1.18.2
* **Full output of `/mv version -p`:** 
Multiverse-Core Version: 4.3.2-SNAPSHOT-b870
Multiverse-NetherPortals Version: 4.2.3-SNAPSHOT-b808
* **Server log:** 
```
20.06 19:17:47 [Server] ERROR Could not pass event PlayerPortalEvent to Multiverse-NetherPortals v4.2.3-SNAPSHOT-b808
20.06 19:17:47 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:126) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
20.06 19:17:47 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
20.06 19:17:47 [Server] INFO at java.lang.Class.forName(Class.java:375) ~[?:?]
20.06 19:17:47 [Server] INFO at com.onarandombox.MultiverseNetherPortals.listeners.MVNPPlayerListener.onPlayerPortal(MVNPPlayerListener.java:71) ~[Multiverse-NetherPortals-4.2.3-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor777.execute(Unknown Source) ~[?:?]
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.level.ServerPlayer.callPortalEvent(ServerPlayer.java:1193) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.Entity.findDimensionEntryPoint(Entity.java:3330) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.server.level.ServerPlayer.findDimensionEntryPoint(ServerPlayer.java:1057) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1110) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.Entity.handleNetherPortal(Entity.java:2765) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.Entity.baseTick(Entity.java:741) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:391) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.Entity.tick(Entity.java:714) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2877) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
20.06 19:17:47 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1623) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
20.06 19:17:47 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
### Details
I was **`not able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by zax71** [comment]
Please follow the issue template. Can we get some reproduction instructions?

**Comment by benwoo1110** [comment]
Unable to reproduce - closing issue
